### PR TITLE
Added modal library component to our project and abstracted it inside signin and signup modal.

### PR DESCRIPTION
**Pull request by soumsps**
This react modal component is built using compound component pattern, it will give more fexibility to user when he/she will be implementing it.

### CODE REVIEW

**Comment by soumsps** [comment]
Preview of the modal: 
image

https://github.com/pesto-students/deep-dive-soumsps/pull/14/commits/11381e1c161b52576513fd07984885060a96e26b  does not contain usage of the modal component to show this dialog on the frontend.

**Comment by soumsps** [comment]
https://github.com/pesto-students/deep-dive-soumsps/pull/14/commits/bce774d9a1e9bd502efb8ee4de4157dc1af59b9f Preview: 
image
image

**Comment by soumsps** [comment]
https://github.com/pesto-students/deep-dive-soumsps/pull/14/commits/5112dd16bcb05c92ae2b12a4d125e27685cf1a1d Preview:

actual form behaviour

This was the required navigation behavior when Sign in or Sign up form is submitted.

**Comment by soumsps** [comment]
Preview of  https://github.com/pesto-students/deep-dive-soumsps/pull/14/commits/6c76f809d4c4798dbc7dc5c7d89c2499b26a4244
Added close button to modal.

image

**Comment by vinodkumartheking** [comment]
#16 Need to work on following features of modal

**Pull request merged**
